### ISSUE TITLE
[AVM Module Issue]: Cannot set static IP addresses for the private endpoint

### ISSUE THREAD

**Issue by djbark** [Azure/terraform-azurerm-avm-res-keyvault-vault#108]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.5.3

### Description

If I set a static IP for the private endpoint within ip_configurations, the terraform build errors:

`│ Private Endpoint Name: "pe-name"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: PrivateEndpointIpConfigurationMissingMemberNamesRequiredByFps: Private Endpoint /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg/providers/Microsoft.Network/privateEndpoints/pe-name contains static ipconfigurations: [PrivateIPAddress: 10.0.0.1, GroupId: vault, MemberName: vault] and its missing these membernames/groupids requested by Private Link service [GroupId: vault, MemberName: default]. Private Endpoint needs to be reconfigured with missing memberNames.`

A simple change to main.private_endpoint.tf fixes this issue.

```
  dynamic "ip_configuration" {
    for_each = each.value.ip_configurations

    content {
      name               = ip_configuration.value.name
      private_ip_address = ip_configuration.value.private_ip_address
      member_name        = "vault" -> "default"
      subresource_name   = "vault"
    }

```

**Comment by matt-FFFFFF** [comment]
fixed by #113
