### ISSUE TITLE
[AVM Module Issue]: 0.6.0 output missing key id required by disk encryption set resources.

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/terraform-azurerm-avm-res-keyvault-vault#120]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.6.0

### Description

The output changes in version 0.6.0 break disk encryption sets that reference key output by id.  Please export the id value along with the resource_id, and resource_versionless_id values.  

Error generated is - `key vault nested item should contain 2 or 3 segments, found 10 segment(s)` .  See the [disk encryption set example](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/disk_encryption_set) usage to see the straight `id` reference instead of the `resource_id` or `resource_versionless_id` references.

**Comment by matt-FFFFFF** [comment]
Hey @jchancellor-ms 

Will add to a patch release
