### ISSUE TITLE
[AVM Module Issue]: Unable to create role assignment at the secret level

### ISSUE THREAD

**Issue by JoaoFHS** [Azure/terraform-azurerm-avm-res-keyvault-vault#138]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.7.1

## Problem

Creating a role assignment at the secret level currently fails. The problem seems to be that the `scope` in the `azurerm_role_assignment` is referring to the `azurerm_key_vault_secret` resource as a whole, instead of pointing to its `id`.

## Example:

Invoking the module with the following configuration:
```bash
module "key_vault" {
  source              = "Azure/avm-res-keyvault-vault/azurerm"
  version             = "0.7.1"
  name                = "my-key-vault"
  location            = "westeurope"
  resource_group_name = "my-rg"
  tenant_id           = "<some-tenant-id>"
  enable_telemetry    = false

  secrets       = {
    app-id-secret = {
      name         = "app_id_secret"
      content_type = "id"
      role_assignments = {
         app-id-secret-reader = {
          role_definition_id_or_name = "Key Vault Secrets User"
          principal_id               = "<principal-id>"
        }
      }
   }
}
```
Throws the following error:
<img width="725" alt="image" src="https://github.com/user-attachments/assets/63b4c3bd-0e81-43d2-9570-912997bc5456">

**Comment by matt-FFFFFF** [comment]
Hi @JoaoFHS this is fixed in the latest commit bit I haven't released!

Apologies...


https://github.com/Azure/terraform-azurerm-avm-res-keyvault-vault/blob/bb6f4574b883e26c834d951e832bd62f35e9f60f/modules/secret/main.tf#L15-L15
