### ISSUE TITLE
[AVM Module Issue]: this AVM is trying to create contacts twice and then it is failing 

### ISSUE THREAD

**Issue by Narnipractice** [Azure/terraform-azurerm-avm-res-keyvault-vault#141]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

 Please find below plan details and we can see that it is trying create twice.
 module.keyvault.azurerm_key_vault.this will be created
  + resource "azurerm_key_vault" "this" {
      + access_policy                   = (known after apply)
      + enable_rbac_authorization       = true
      + enabled_for_deployment          = false
      + enabled_for_disk_encryption     = false
      + enabled_for_template_deployment = false
      + id                              = (known after apply)
      + location                        = "eastus"
      + name                            = "test-kv11234ddazre"
      + public_network_access_enabled   = true
      + purge_protection_enabled        = true
      + resource_group_name             = "test"
      + sku_name                        = "premium"
      + soft_delete_retention_days      = 90
      + tenant_id                       = ""
      + vault_uri                       = (known after apply)

      + contact {
          + email = "example@gmail.com"
          + name  = "null"
          + phone = "null"
        }

      + network_acls {
          + bypass         = "None"
          + default_action = "Deny"
        }
    }

  # module.keyvault.azurerm_key_vault_certificate_contacts.this[0] will be created
  + resource "azurerm_key_vault_certificate_contacts" "this" {
      + id           = (known after apply)
      + key_vault_id = (known after apply)

      + contact {
          + email = "example@gmail.com"
          + name  = "null"
          + phone = "null"
        }
    }

**Comment by matt-FFFFFF** [comment]
Yes you're right! Will fix now
