### ISSUE TITLE
[AVM Module Issue]: this_unmanaged_dns_zone_groups still tries to reset private_dns_zone_group

### ISSUE THREAD

**Issue by Hi-Fi** [Azure/terraform-azurerm-avm-res-keyvault-vault#144]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.7.1

### Description

When trying to move from separate private endpoint resource to use this module created private endpoint, new version from module still tries to clear out `private_dns_zone_group` settings. It't not enough that those are left without creation in module, also the content should be ignired

## Reproduction
- Create Private endpoint with some DNS settings (with e.g. Terraform)
- Add this AVM module with `private_endpoints_manage_dns_zone_group: false`
- Remove original endpoint from state and import one created with module
- Check Terraform plan (can be targetted just to the module)

## Expected outcome
No changes in plan

## Actual outcome
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.KeyVault.azurerm_private_endpoint.this_unmanaged_dns_zone_groups["PrivateEndpoint"] will be updated in-place
  ~ resource "azurerm_private_endpoint" "this_unmanaged_dns_zone_groups" {
        id                            = "<valid id of PEP>"
        name                          = "test-pep"
        tags                          = {}
        # (7 unchanged attributes hidden)

      - private_dns_zone_group {
          - id                   = "<valid id of PEP>/privateDnsZoneGroups/deployedByPolicy" -> null
          - name                 = "deployedByPolicy" -> null
          - private_dns_zone_ids = [
              - "<valid ID of original private DNS zone>",
            ] -> null
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

**Comment by matt-FFFFFF** [comment]
Apologies, I missed the ignore_changes! Will fox now
