### ISSUE TITLE
Terraform version restrictions should be at least 1.6

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/terraform-azurerm-avm-res-keyvault-vault#17]
The terraform minimum version in https://github.com/Azure/terraform-azurerm-avm-res-keyvault-vault/blob/main/terraform.tf does not  support strcontains function that is used in the module resulting in errors when the version is below 1.6.  

Recommend updating the terraform minimum version requirement to 1.6

**Comment by matt-FFFFFF** [comment]
Thanks @jchancellor-ms good catch - will do
