### ISSUE TITLE
[AVM Module Issue]: e2e testing issue in workflow

### ISSUE THREAD

**Issue by Vairaml** [Azure/terraform-azurerm-avm-res-keyvault-vault#170]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

I am getting the error when i using the self hosted agent for e2e testing in workflow. I am using the private repo
Please suggest on this.

ERROR: argument --username/-u: expected one argument
Examples from AI knowledge base:
az login --identity --username 00000000-0000-0000-0000-000000000000
Log in with a user-assigned managed identity. You must specify the client ID, object ID or resource ID of the user-assigned managed identity with --username.
az login --identity
Log in with a system-assigned managed identity.
az login -u johndoe@contoso.com -p VerySecret
Log in with username and password. This doesn't work with Microsoft accounts or accounts that have two-factor authentication enabled. Use -p=secret if the first character of the password is '-'.
https://aka.ms/cli_ref
Read more about the command in reference docs
ERROR: argument --username/-u: expected one argument
Examples from AI knowledge base:
az login --identity --username 00000000-0000-0000-0000-000000000000
Log in with a user-assigned managed identity. You must specify the client ID, object ID or resource ID of the user-assigned managed identity with --username.
az login --identity
Log in with a system-assigned managed identity.
az login -u johndoe@contoso.com -p VerySecret
Log in with username and password. This doesn't work with Microsoft accounts or accounts that have two-factor authentication enabled. Use -p=secret if the first character of the password is '-'.

**Comment by matt-FFFFFF** [comment]
Hi you need to configure OIDC for authentication. We no longer support managed identity.

Suggest creating a user assigned managed identity and adding federated credentials.

You then need to configure the tenant, client and subscription id environment variables.

**Comment by matt-FFFFFF** [comment]
#rr

**Comment by Vairaml** [comment]
Can you provide the sample repo where you configured OIDC for authentication.. I am asking for my reference.

**Comment by Vairaml** [comment]
My self-hosted runner does not support the docker, is there any other methods to test

**Comment by matt-FFFFFF** [comment]
Am slightly confused about docker comment but you can still use OIDC with self hosted runners.

**Comment by matt-FFFFFF** [comment]
#RR
