### ISSUE TITLE
Be able to control soft_delete_retention_days

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-avm-res-keyvault-vault#22]
Since purge_protection can be controlled it makes sense to control `soft_delete_retention_days` too

**Comment by matt-FFFFFF** [comment]
Goood idea. I will add it to the backlog.

**Comment by davidkarlsen** [comment]
BTW: If you use tfsec you'll get automatic lint/warning for this.

**Comment by matt-FFFFFF** [comment]
We plan to introduce this to our ci tooling

**Comment by davidkarlsen** [comment]
Do you accept PRs? It would be great with a release support this - then we can start using this module.

**Comment by matt-FFFFFF** [comment]
Of course!

Please feel free

**Comment by matt-FFFFFF** [comment]
@davidkarlsen I have a PR for this now - will merge and release today
