### ISSUE TITLE
make role_assignments a set of objects instead

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-avm-res-keyvault-vault#23]
there us no use of the map key in `role_assignments` - hence it makes sense to make this a set instead

**Comment by matt-FFFFFF** [comment]
The problem with doing that is Terraform needs a map to use for_each.

Sure, you can construct a for_each map using the data from the objects, but then you run the very real risk of the map key being unknown at plan time. This causes a failure.

This method where we use an arbitrary map key, whilst on the surface seems more cumbersome, is much more robust once you start using these modules in more complex scenarios.

**Comment by davidkarlsen** [comment]
you can iterate on sets as well: https://developer.hashicorp.com/terraform/language/meta-arguments/for_each#using-sets - each item is `each.value`

**Comment by davidkarlsen** [comment]
but no biggie to keep as-is.

**Comment by matt-FFFFFF** [comment]
It's a map (of anything) or a set of strings only I'm afraid:

> If a resource or module block includes a for_each argument whose value is a map or a set of strings, Terraform creates one instance for each member of that map or set.

Source: https://developer.hashicorp.com/terraform/language/meta-arguments/for_each

**Comment by davidkarlsen** [comment]
ah, my bad - thanks again for the reference!
