### ISSUE TITLE
consider standard as default sku

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-avm-res-keyvault-vault#24]
Isn't `premium` as default a bit over the top?

**Comment by matt-FFFFFF** [comment]
Azure Verified Modules aligns to the below:

https://azure.github.io/Azure-Verified-Modules/faq/#what-does-avm-mean-by-waf-aligned

We are aiming to become secure by default, available by default. Premium grants the use of HSM backed keys hence it's the default.

**Comment by davidkarlsen** [comment]
OK, that makes sense - thanks for the explaination!
