### ISSUE TITLE
Use azurerm_key_vault_certificate_contacts instead

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-avm-res-keyvault-vault#25]
See https://github.com/hashicorp/terraform-provider-azurerm/pull/19743 and https://github.com/hashicorp/terraform-provider-azurerm/issues/10256 - it might be more optimal to use `azurerm_key_vault_certificate_contacts` to avoid permission problem when initially creating the KV.

**Comment by davidkarlsen** [comment]
ah, nvm, this is of course on the consuming-side of things.

**Comment by matt-FFFFFF** [comment]
Thanks for this. We will consider the implementation detail.

We do not support access policies in the module as yet, preferring Azure role assignments.

In your use case, how would the above affect the use of the dedicated contact resource?

**Comment by davidkarlsen** [comment]
you get a permission denied because the IAM has not been assigned yet - so instead you get this sequence:
1) create KV
2) create IAM
3) create contact resource, depending on 2)

**Comment by matt-FFFFFF** [comment]
Thanks. Will swap it out and make dependent on the role assignments

**Comment by davidkarlsen** [comment]
could this be merged and released?

**Comment by matt-FFFFFF** [comment]
Hi, I've put this in another PR that's challenging at the moment.

I can pull it out.

**Comment by davidkarlsen** [comment]
@matt-FFFFFF fix in #39
