### ISSUE TITLE
Does this support RBAC as opposed to 'keyvault policies' for permission control?

### ISSUE THREAD

**Issue by munntjlx** [Azure/terraform-azurerm-avm-res-keyvault-vault#27]
Mostly curious if this supports keyvault RBAC, or just the 'old' keyvault policies methodology?

**Comment by matt-FFFFFF** [comment]
Hi,

We only support the new Azure roleAssignment way.

**Comment by matt-FFFFFF** [comment]
Closing for now. Please reopen if you need.
