### ISSUE TITLE
Support set of IDs in role_assignments

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-avm-res-keyvault-vault#29]
It would be nice if one could give the principals to give access for a given role as a set instead of a single ID.

```
role_assignments = {
+    admins = {
+      role_definition_id_or_name = "Key Vault Administrator"
+      principal_id               = data.azuread_groups.admin_groups.object_ids[0]
+    }
+  }
```

instead:
```
role_assignments = {
+    admins = {
+      role_definition_id_or_name = "Key Vault Administrator"
+      principal_ids               = data.azuread_groups.admin_groups.object_ids
+    }
+  }
```

single principal is just a special case (a set with one entry) - makes it easier to assign more

**Comment by matt-FFFFFF** [comment]
Hi,

Thanks for the suggestion.

I agree that this would be more efficient.

I think we will come across an issue whereby we have to construct the keys of the for_each loop.

We would need to combine the original map key with the principal_id.

In the case that the principal id was a string this would be ok. However, we often create the principal (e.g. Entra ID group) in the same apply and, as such, the principal id would not be known until after the apply. This would cause an error with the for_each loop.

It's very annoying but I think we must continue with the current approach.

Thoughts?

**Comment by davidkarlsen** [comment]
ok - just one of terraforms wonders - good to see good tf experience driving decisions here instead :-)
