### ISSUE TITLE
feat: certificate support

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/terraform-azurerm-avm-res-keyvault-vault#34]
@matt-FFFFFF  - Based on the feedback from the customer,  requesting two features 

  Support for certificates

**Comment by matt-FFFFFF** [comment]
Work underway in associated branch

**Comment by jchancellor-ms** [comment]
@matt-FFFFFF - Doing issue Triage and it appears there was a release back in November of last year that was supposed to close this issue.  Can this issue be closed or is there additional work to be done?

**Comment by matt-FFFFFF** [comment]
Hi I have key and secret support but not cert - still needs adding

**Comment by piotrkurylak** [comment]
Hi, 

Please don't forget about certificates outputs.

Thank you!

**Comment by matt-FFFFFF** [comment]
Hi experimenting with this I don't think it belongs in the module. Certs are a data plane resource and it's perfectly possible to add certificates to a KV outside this module, using the outputs.
