### ISSUE TITLE
Question for .github/policies files usage

### ISSUE THREAD

**Issue by VincentVerweij** [Azure/terraform-azurerm-avm-res-keyvault-vault#5]
Hi @matt-FFFFFF,

Not an issue but a question. 
How is the [.github/policies/branchprotection.yml](https://github.com/Azure/terraform-azurerm-avm-res-keyvault-vault/blob/main/.github/policies/branchprotection.yml) file used?
I was looking for this online but couldn't find any information about it.

Thanks,
Vincent

**Comment by matt-FFFFFF** [comment]
Hi,

this is an internal MSFT policy tool that is used to control repos.
