### ISSUE TITLE
feat: access policies

### ISSUE THREAD

**Issue by vjmanda** [Azure/terraform-azurerm-avm-res-keyvault-vault#60]
The module assumes access permission model `enable_rbac_authorization = true`. Though this is the recommended approach, it should ideally be configurable using a boolean. Additionally the module needs to support [Access Policy Entry](https://learn.microsoft.com/en-us/rest/api/keyvault/keyvault/vaults/update-access-policy?view=rest-keyvault-keyvault-2022-07-01&tabs=HTTP#accesspolicyentry) by either using [access_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#access_policy) or 
[azurerm_key_vault_access_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy).

**Comment by matt-FFFFFF** [comment]
Hi there - we intentionally released this without access policy support due to the AVM standards of adhering to best practices. We hear you and will this to the backlog for consideration.

**Comment by vjmanda** [comment]
> Hi there - we intentionally released this without access policy support due to the AVM standards of adhering to best practices. We hear you and will this to the backlog for consideration.

Thanks Matt, I understand. However, I'd recommend better standardisation across Bicep and Terraform AVMs as bicep seems to already support access policies.

**Comment by Menghua1** [comment]
@jongio for notification.
