### ISSUE TITLE
[AVM Module Issue]: create-key example specify an unexisting parameter "key_vault_id". It should be removed

### ISSUE THREAD

**Issue by bryansan-msft** [Azure/terraform-azurerm-avm-res-keyvault-vault#90]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### (Optional) Module Version

0.5.3

### Description

In the module it is using the key vault id that is being created. Having this value in the example is really confusing. 

![image](https://github.com/Azure/terraform-azurerm-avm-res-keyvault-vault/assets/117635118/c32d75ed-55a4-4652-8039-ba4c03124d86)

**Comment by matt-FFFFFF** [comment]
fixed by #113

**Comment by matt-FFFFFF** [comment]
Thanks for flagging - this was causing a huge cycle error 😆
