### ISSUE TITLE
[AVM Module Issue]: Key vault name validation incorrect

### ISSUE THREAD

**Issue by captainhook** [Azure/terraform-azurerm-avm-res-keyvault-vault#98]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.5.3

### Description

The current condition for key vault name is `        condition     = can(regex("^[a-z0-9-]{3,24}$", var.name))` which is not in line with Microsoft's guidance.

As per official documentation

| Entity                | Scope          | Length | Valid Characters                                                                                                |
| --------------------- | -------------- | ------ | --------------------------------------------------------------------------------------------------------------- |
| ...                   | ...            | ...    | ...                                                                                                             |
| vaults | global | 3-24   | Alphanumerics and hyphens.<br />Start with letter. End with letter or digit. Can't contain consecutive hyphens. |

source: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

**Comment by matt-FFFFFF** [comment]
This will be fixed in the next release

**Comment by matt-FFFFFF** [comment]
fixed by #113

**Comment by captainhook** [comment]
@matt-FFFFFF this is still incorrect.

Please re-open.
